/** Đồng bộ với ShuttleUp.Backend.Constants.NotificationTypes */
export const NOTIFICATION_TYPES = {
  BOOKING_NEW: 'BOOKING_NEW',
  BOOKING: 'BOOKING',
  COURT_BLOCK: 'COURT_BLOCK',
  PAYMENT_PROOF: 'PAYMENT_PROOF',
  SYSTEM: 'SYSTEM',
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  FRIEND_ACCEPTED: 'FRIEND_ACCEPTED',

  // Matching
  MATCHING_JOIN_REQUEST: 'MATCHING_JOIN_REQUEST',
  MATCHING_JOIN_ACCEPTED: 'MATCHING_JOIN_ACCEPTED',
  MATCHING_JOIN_REJECTED: 'MATCHING_JOIN_REJECTED',
  MATCHING_MEMBER_KICKED: 'MATCHING_MEMBER_KICKED',
  MATCHING_POST_CLOSED: 'MATCHING_POST_CLOSED',
  MATCHING_POST_CANCELLED: 'MATCHING_POST_CANCELLED',
  MATCHING_NEW_COMMENT: 'MATCHING_NEW_COMMENT',
  MATCHING_COMMENT_REPLY: 'MATCHING_COMMENT_REPLY',

  // Refund
  REFUND_REQUEST: 'REFUND_REQUEST',
  REFUND_COMPLETED: 'REFUND_COMPLETED',
  REFUND_REJECTED: 'REFUND_REJECTED',
  REFUND_RECONCILED: 'REFUND_RECONCILED',

  // Venue reviews
  VENUE_REVIEW_NEW: 'VENUE_REVIEW_NEW',
  VENUE_REVIEW_REPLY: 'VENUE_REVIEW_REPLY',

  // Reminders
  UPCOMING_BOOKING: 'UPCOMING_BOOKING',
  BOOKING_MANAGER_REMINDER: 'BOOKING_MANAGER_REMINDER',

  // Disputes
  DISPUTE_REFUND_PENDING_PLAYER: 'DISPUTE_REFUND_PENDING_PLAYER',
  DISPUTE_REFUND_PENDING_MANAGER: 'DISPUTE_REFUND_PENDING_MANAGER',

  // Reports
  REPORT_RESOLVED: 'REPORT_RESOLVED',
  REPORT_REJECTED: 'REPORT_REJECTED',
  REPORT_TARGET_ACTION: 'REPORT_TARGET_ACTION',

  // Manager Requests
  MANAGER_REQUEST_SUBMITTED: 'MANAGER_REQUEST_SUBMITTED',
  MANAGER_REQUEST_APPROVED: 'MANAGER_REQUEST_APPROVED',
  MANAGER_REQUEST_REJECTED: 'MANAGER_REQUEST_REJECTED',

  // Profile
  PROFILE_UPDATED: 'PROFILE_UPDATED',
};
