/** Đồng bộ với ShuttleUp.Backend.Constants.NotificationTypes */
export const NOTIFICATION_TYPES = {
  BOOKING_NEW: 'BOOKING_NEW',
  BOOKING: 'BOOKING',
  PAYMENT_PROOF: 'PAYMENT_PROOF',
  SYSTEM: 'SYSTEM',
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  FRIEND_ACCEPTED: 'FRIEND_ACCEPTED',

  MATCHING_JOIN_REQUEST: 'MATCHING_JOIN_REQUEST',
  MATCHING_JOIN_ACCEPTED: 'MATCHING_JOIN_ACCEPTED',
  MATCHING_JOIN_REJECTED: 'MATCHING_JOIN_REJECTED',
  MATCHING_MEMBER_KICKED: 'MATCHING_MEMBER_KICKED',
  MATCHING_POST_CLOSED: 'MATCHING_POST_CLOSED',
  MATCHING_NEW_COMMENT: 'MATCHING_NEW_COMMENT',
  MATCHING_COMMENT_REPLY: 'MATCHING_COMMENT_REPLY',

  VENUE_REVIEW_NEW: 'VENUE_REVIEW_NEW',
  VENUE_REVIEW_REPLY: 'VENUE_REVIEW_REPLY',
};
